// ============================================================
// ML Onset Detection Pipeline — onset_ml.rs
//
// Pipeline: audio decode (symphonia) → resample to 44.1 kHz (rubato)
// → 3 log-mel spectrograms at FFT 1024/2048/4096 with ddc_onset's
// zero-phase windowing + preloaded mel matrices → per-bin z-score
// normalization → ddc_onset placement CNN (ONNX) → per-frame onset
// probability → silence gate → OnsetBundle.
//
// Recent change (Phase B of onset plan, 2026-04-20): Replaced the
// madmom CNN with Chris Donahue's `ddc_onset` placement network
// (trained on DDR chart annotations). Three user-visible impacts:
//   1) Output density drops from ~9.5/sec to a musically-clean
//      range controlled by the frontend peak-picker's density budget.
//   2) Output is wrapped in an `OnsetBundle { version, frames }`
//      envelope so the frontend can detect pipeline skew on upgrades
//      (see EXPECTED_ONSET_PIPELINE_VERSION on the TS side).
//   3) Preprocessing NO LONGER builds its own mel filterbank or
//      stacks 15-frame context; ddc_onset's exported graph does its
//      own ±7-frame padding + unfold internally. We compute
//      [num_frames, 80, 3] normalized log-mel and pass it in as a
//      single input — CHALLENGE difficulty is baked into the graph,
//      density selection happens in the frontend peak-picker.
//
// Constants and binary artifact layouts are generated by
// `scripts/convert_ddc_to_onnx.py` and documented in its header.
// ============================================================

use ndarray::Array3;
use ort::session::Session;
use ort::session::builder::GraphOptimizationLevel;
use ort::value::Tensor;
use rayon::prelude::*;
use realfft::RealFftPlanner;
use rubato::{Resampler, SincFixedIn, SincInterpolationParameters,
             SincInterpolationType, WindowFunction};
use serde::Serialize;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};
use tauri::Manager;

// ── Pipeline constants (mirrored in scripts/convert_ddc_to_onnx.py) ──

/// Target sample rate — ddc_onset was trained on 44.1 kHz audio.
const SAMPLE_RATE: u32 = 44100;

/// Hop size = SAMPLE_RATE / FRAME_RATE = 441, producing 100 fps output.
const HOP_SIZE: usize = 441;

/// Number of mel frequency bands per FFT channel.
const NUM_MEL_BANDS: usize = 80;

/// ddc_onset's three FFT window sizes, in the channel order the exported
/// graph expects. **DO NOT** reorder without rebuilding the ONNX — the mel
/// matrices in ddc_onset_extractor.bin are keyed to this exact sequence.
const FFT_SIZES: [usize; 3] = [1024, 2048, 4096];

/// Log-compression floor — `ln(energy + LOG_EPS)`. Matches ddc_onset's
/// spectral.py `_LOG_EPS = 1e-16`.
const LOG_EPS: f64 = 1e-16;

/// Rubato resampler chunk size (samples per processing block).
const RESAMPLE_CHUNK: usize = 1024;

/// Silence gate threshold (mean-squared amplitude). Frames with RMS below
/// this are zeroed — the CNN can hallucinate onsets in silence because
/// silent log-mel values sit outside its training distribution.
const SILENCE_THRESHOLD: f32 = 1e-4;

/// Pipeline version carried in the IPC envelope. Bump when the output
/// shape or the meaning of `OnsetResult` changes so the frontend cache
/// invalidates cleanly across upgrades. Must match
/// `EXPECTED_ONSET_PIPELINE_VERSION` in src/utils/ipc.ts.
pub const ONSET_PIPELINE_VERSION: u32 = 2;

// ── Types ───────────────────────────────────────────────────────

/// One onset probability sample at 100 fps. Field layout is stable across
/// pipeline versions — version changes are communicated via OnsetBundle
/// and do NOT necessarily alter per-frame semantics.
#[derive(Debug, Serialize, Clone)]
pub struct OnsetResult {
    /// Time in seconds from the start of the audio file.
    pub time: f64,
    /// Onset probability 0.0-1.0 (higher = more confident).
    pub probability: f64,
}

/// Versioned envelope returned by `detect_onsets_ml`. The frontend checks
/// `version` against its compiled-in expectation and busts the salience
/// cache on mismatch — see src/hooks/useOnsetDetection.ts.
#[derive(Debug, Serialize, Clone)]
pub struct OnsetBundle {
    pub version: u32,
    pub frames: Vec<OnsetResult>,
}

/// SpectrogramExtractor constants loaded from `ddc_onset_extractor.bin`.
/// Layout (little-endian f32, generated by scripts/convert_ddc_to_onnx.py):
///
///     for fft_size in [1024, 2048, 4096]:
///         window[fft_size]              # pre-computed Hann-like window
///         mel[(fft_size/2 + 1) × 80]    # librosa mel matrix, row-major
///
/// One instance is constructed lazily per app lifetime and cached in
/// EXTRACTOR below.
struct Extractor {
    /// Per-FFT-size pre-windowed coefficients. Index matches FFT_SIZES.
    windows: [Vec<f64>; 3],
    /// Per-FFT-size dense mel matrices. Shape `[(fft_size/2+1), 80]`,
    /// stored row-major so `mel[bin][mel_band]` is a flat access.
    mels: [Vec<Vec<f64>>; 3],
}

/// Per-bin z-score moments loaded from `ddc_onset_normalizer.bin`.
///
///     mean[80 × 3]  # row-major, [mel_band][fft_channel]
///     std[80 × 3]   # same layout
struct Normalizer {
    /// `mean[mel_band][fft_channel]` — 80 × 3 = 240 f32 values.
    mean: Vec<Vec<f32>>,
    /// `std[mel_band][fft_channel]` — 80 × 3 = 240 f32 values.
    std: Vec<Vec<f32>>,
}

// ── Lazy caches ─────────────────────────────────────────────────

/// Cached ONNX session. Stores `Result<_, String>` so init failures are
/// reported on every retry, not just the first (missing model, corrupt
/// ONNX graph, unsupported CPU features — all crash the pipeline without
/// this caching pattern).
static ONSET_SESSION: OnceLock<Result<Mutex<Session>, String>> = OnceLock::new();

/// Cached SpectrogramExtractor constants. Binary file is ~1.15 MB and
/// read once per app lifetime.
static EXTRACTOR: OnceLock<Result<Extractor, String>> = OnceLock::new();

/// Cached SpectrogramNormalizer constants. Binary file is 1.9 KB.
static NORMALIZER: OnceLock<Result<Normalizer, String>> = OnceLock::new();

// ═══════════════════════════════════════════════════════════════
// 1. AUDIO DECODING
// (Unchanged from the madmom-era pipeline — same 44.1 kHz mono out.)
// ═══════════════════════════════════════════════════════════════

/// Decode any supported audio file to mono f32 samples at 44100 Hz.
fn decode_audio_mono(path: &Path) -> Result<Vec<f32>, String> {
    use symphonia::core::audio::SampleBuffer;
    use symphonia::core::codecs::DecoderOptions;
    use symphonia::core::formats::FormatOptions;
    use symphonia::core::io::MediaSourceStream;
    use symphonia::core::meta::MetadataOptions;
    use symphonia::core::probe::Hint;

    let file = std::fs::File::open(path)
        .map_err(|e| format!("Cannot open audio file: {}", e))?;
    let mss = MediaSourceStream::new(Box::new(file), Default::default());

    let mut hint = Hint::new();
    if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
        hint.with_extension(ext);
    }

    let probe_result = symphonia::default::get_probe()
        .format(&hint, mss, &FormatOptions::default(), &MetadataOptions::default())
        .map_err(|e| format!("Cannot probe audio format: {}", e))?;

    let mut format_reader = probe_result.format;

    let track = format_reader.default_track()
        .ok_or("No audio track found in file")?;
    let track_id = track.id;
    let sample_rate = track.codec_params.sample_rate
        .ok_or("Cannot determine sample rate")?;
    let channels = track.codec_params.channels
        .map(|ch| ch.count())
        .unwrap_or(1);

    let mut decoder = symphonia::default::get_codecs()
        .make(&track.codec_params, &DecoderOptions::default())
        .map_err(|e| format!("Cannot create audio decoder: {}", e))?;

    let mut all_samples: Vec<f32> = Vec::new();
    loop {
        match format_reader.next_packet() {
            Ok(packet) => {
                if packet.track_id() != track_id {
                    continue;
                }
                match decoder.decode(&packet) {
                    Ok(decoded) => {
                        let mut sample_buf = SampleBuffer::<f32>::new(
                            decoded.capacity() as u64,
                            *decoded.spec(),
                        );
                        sample_buf.copy_interleaved_ref(decoded);
                        all_samples.extend_from_slice(sample_buf.samples());
                    }
                    Err(symphonia::core::errors::Error::DecodeError(_)) => continue,
                    Err(e) => return Err(format!("Decode error: {}", e)),
                }
            }
            Err(symphonia::core::errors::Error::IoError(ref e))
                if e.kind() == std::io::ErrorKind::UnexpectedEof => break,
            Err(e) => return Err(format!("Read error: {}", e)),
        }
    }

    if all_samples.is_empty() {
        return Err("No audio samples decoded".to_string());
    }

    let mono: Vec<f32> = if channels > 1 {
        all_samples.chunks(channels)
            .map(|frame| frame.iter().sum::<f32>() / channels as f32)
            .collect()
    } else {
        all_samples
    };

    if sample_rate != SAMPLE_RATE {
        resample_to_44100(&mono, sample_rate)
    } else {
        Ok(mono)
    }
}

/// Resample audio from `source_rate` to 44100 Hz using sinc interpolation.
fn resample_to_44100(samples: &[f32], source_rate: u32) -> Result<Vec<f32>, String> {
    let ratio = SAMPLE_RATE as f64 / source_rate as f64;

    let params = SincInterpolationParameters {
        sinc_len: 256,
        f_cutoff: 0.95,
        interpolation: SincInterpolationType::Linear,
        oversampling_factor: 256,
        window: WindowFunction::BlackmanHarris2,
    };

    let mut resampler = SincFixedIn::<f32>::new(
        ratio,
        2.0,
        params,
        RESAMPLE_CHUNK,
        1,
    ).map_err(|e| format!("Resampler init: {}", e))?;

    let mut output = Vec::with_capacity((samples.len() as f64 * ratio) as usize + 1024);

    for chunk in samples.chunks(RESAMPLE_CHUNK) {
        let mut input_chunk = vec![chunk.to_vec()];
        if input_chunk[0].len() < RESAMPLE_CHUNK {
            input_chunk[0].resize(RESAMPLE_CHUNK, 0.0);
        }
        let resampled = resampler.process(&input_chunk, None)
            .map_err(|e| format!("Resample: {}", e))?;
        output.extend_from_slice(&resampled[0]);
    }

    Ok(output)
}

// ═══════════════════════════════════════════════════════════════
// 2. CONSTANT LOADING (ddc_onset_extractor.bin, ddc_onset_normalizer.bin)
// ═══════════════════════════════════════════════════════════════

/// Read a `.bin` file and interpret it as a flat Vec<f32>. The file is
/// written by convert_ddc_to_onnx.py as raw little-endian f32 bytes in a
/// documented layout; the callers below split the flat vector into the
/// per-field slices they need.
fn read_f32_le(path: &Path) -> Result<Vec<f32>, String> {
    let bytes = std::fs::read(path)
        .map_err(|e| format!("Cannot read {}: {}", path.display(), e))?;
    if bytes.len() % 4 != 0 {
        return Err(format!(
            "{} has {} bytes, not a multiple of 4 (expected f32 little-endian)",
            path.display(), bytes.len()
        ));
    }
    let mut out = Vec::with_capacity(bytes.len() / 4);
    for chunk in bytes.chunks_exact(4) {
        out.push(f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]));
    }
    Ok(out)
}

/// Parse `ddc_onset_extractor.bin` into per-FFT-size windows + mel matrices.
///
/// File layout (matches convert_ddc_to_onnx.py::write_extractor_bin):
///
///     window_1024 (1024 f32) → mel_1024 (513 × 80 f32)
///     window_2048 (2048 f32) → mel_2048 (1025 × 80 f32)
///     window_4096 (4096 f32) → mel_4096 (2049 × 80 f32)
///
/// Windows are promoted to f64 at load time so the inner FFT loop stays
/// in f64 (matches ddc_onset's numerical regime).
fn load_extractor(path: &Path) -> Result<Extractor, String> {
    let flat = read_f32_le(path)?;
    let mut cursor = 0usize;

    // Initialize with empty Vec so we can fill by index.
    let mut windows: [Vec<f64>; 3] = [Vec::new(), Vec::new(), Vec::new()];
    let mut mels: [Vec<Vec<f64>>; 3] = [Vec::new(), Vec::new(), Vec::new()];

    for (ch, &fft_size) in FFT_SIZES.iter().enumerate() {
        let n_bins = fft_size / 2 + 1;

        // Pull window of length fft_size.
        if cursor + fft_size > flat.len() {
            return Err(format!(
                "ddc_onset_extractor.bin truncated: expected window[{}] at offset {} but only {} f32 remain",
                fft_size, cursor, flat.len() - cursor
            ));
        }
        let window_f32 = &flat[cursor..cursor + fft_size];
        windows[ch] = window_f32.iter().map(|&v| v as f64).collect();
        cursor += fft_size;

        // Pull mel matrix of shape [n_bins, 80], row-major.
        let mel_entries = n_bins * NUM_MEL_BANDS;
        if cursor + mel_entries > flat.len() {
            return Err(format!(
                "ddc_onset_extractor.bin truncated: expected mel[{}x{}] at offset {}",
                n_bins, NUM_MEL_BANDS, cursor
            ));
        }
        let mut mel = Vec::with_capacity(n_bins);
        for bin in 0..n_bins {
            let row_start = cursor + bin * NUM_MEL_BANDS;
            let row = flat[row_start..row_start + NUM_MEL_BANDS]
                .iter().map(|&v| v as f64).collect::<Vec<f64>>();
            mel.push(row);
        }
        mels[ch] = mel;
        cursor += mel_entries;
    }

    if cursor != flat.len() {
        return Err(format!(
            "ddc_onset_extractor.bin has {} trailing f32 values after expected layout",
            flat.len() - cursor
        ));
    }
    Ok(Extractor { windows, mels })
}

/// Parse `ddc_onset_normalizer.bin` into mean + std matrices of shape
/// [80, 3]. File layout: mean (80 × 3 f32, row-major), then std (same).
fn load_normalizer(path: &Path) -> Result<Normalizer, String> {
    let flat = read_f32_le(path)?;
    let expected = NUM_MEL_BANDS * FFT_SIZES.len() * 2;
    if flat.len() != expected {
        return Err(format!(
            "ddc_onset_normalizer.bin has {} f32, expected {} (= 80 × 3 × 2)",
            flat.len(), expected
        ));
    }

    let half = flat.len() / 2;
    let mut mean = Vec::with_capacity(NUM_MEL_BANDS);
    let mut std = Vec::with_capacity(NUM_MEL_BANDS);
    for band in 0..NUM_MEL_BANDS {
        let m_start = band * FFT_SIZES.len();
        mean.push(flat[m_start..m_start + FFT_SIZES.len()].to_vec());
        let s_start = half + band * FFT_SIZES.len();
        std.push(flat[s_start..s_start + FFT_SIZES.len()].to_vec());
    }
    Ok(Normalizer { mean, std })
}

// ═══════════════════════════════════════════════════════════════
// 3. LOG-MEL SPECTROGRAM (ddc_onset-compatible)
//
// Mirror of ddc_onset/spectral.py::SpectrogramExtractor.forward. Three
// things differ from the madmom-era pipeline:
//
//   1) Waveform is LEFT-PADDED by fft_size/2 zeros so frame centers align
//      with audio sample timestamps 0, HOP, 2*HOP, ...
//   2) After windowing, each frame's two halves are SWAPPED before FFT
//      ("zero-phase" windowing, inherited from essentia; see
//      https://github.com/MTG/essentia/blob/master/src/algorithms/standard/windowing.cpp#L85).
//   3) Mel projection uses a preloaded matrix (from extractor.bin) rather
//      than a triangular filterbank computed here.
// ═══════════════════════════════════════════════════════════════

/// Compute a log-mel spectrogram for one FFT size. Returns a row-major
/// `[num_frames, 80]` f32 matrix. `window` and `mel` come from
/// `Extractor` and are keyed to the FFT size — caller must pass the
/// matching pair.
fn compute_log_mel_ddc(
    samples: &[f32],
    fft_size: usize,
    window: &[f64],
    mel: &[Vec<f64>],
) -> Result<Vec<Vec<f32>>, String> {
    let half = fft_size / 2;
    let n_bins = fft_size / 2 + 1;
    debug_assert_eq!(window.len(), fft_size);
    debug_assert_eq!(mel.len(), n_bins);

    // ddc_onset left-pads the waveform with fft_size/2 zeros so the first
    // frame's center corresponds to audio sample 0. We emulate by computing
    // `padded_len = samples.len() + half` and iterating frame starts in the
    // PADDED coordinate system, reading from `samples` with a left-offset.
    let padded_len = samples.len() + half;
    // Number of frames = ceil(padded_len / HOP); the last ~fft_size/HOP
    // frames will be partial (left-padded with zeros).
    let num_frames = (padded_len + HOP_SIZE - 1) / HOP_SIZE;

    let mut planner = RealFftPlanner::<f64>::new();
    let fft = planner.plan_fft_forward(fft_size);
    let mut input_buf = vec![0.0f64; fft_size];
    let mut spectrum = fft.make_output_vec();

    let mut spectrogram = Vec::with_capacity(num_frames);

    for frame_idx in 0..num_frames {
        let padded_start = frame_idx * HOP_SIZE;

        // Fill input_buf with windowed samples from the PADDED waveform.
        // Padded index i corresponds to original-audio index (i - half).
        for i in 0..fft_size {
            let padded_idx = padded_start + i;
            let sample = if padded_idx < half {
                // In the left-pad region.
                0.0f64
            } else {
                let audio_idx = padded_idx - half;
                if audio_idx < samples.len() {
                    samples[audio_idx] as f64
                } else {
                    // Past audio end — zero-pad.
                    0.0f64
                }
            };
            input_buf[i] = sample * window[i];
        }

        // Zero-phase windowing: swap halves so the window's peak is at the
        // start of the buffer. This makes the DFT's zero-phase reference
        // coincide with the window center, matching essentia/ddc_onset.
        for i in 0..half {
            input_buf.swap(i, i + half);
        }

        // Forward FFT (real → complex, positive frequencies only).
        fft.process(&mut input_buf, &mut spectrum)
            .map_err(|e| format!("FFT at frame {} size {}: {}", frame_idx, fft_size, e))?;

        // Power spectrogram: |X[k]|² — ddc_onset uses power, not magnitude.
        // See spectral.py: `spec_r*spec_r + spec_i*spec_i` (no sqrt).
        let mut power = vec![0.0f64; n_bins];
        for (k, c) in spectrum.iter().take(n_bins).enumerate() {
            power[k] = c.re * c.re + c.im * c.im;
        }

        // Mel projection: energy[b] = sum_k mel[k][b] * power[k].
        // The mel matrix is stored row-major per-bin (n_bins × 80), so
        // we scan the n_bins × 80 multiply-adds in the natural order.
        let mut mel_frame = vec![0.0f32; NUM_MEL_BANDS];
        let mut mel_acc = vec![0.0f64; NUM_MEL_BANDS];
        for k in 0..n_bins {
            let p = power[k];
            if p == 0.0 {
                continue;
            }
            let row = &mel[k];
            for b in 0..NUM_MEL_BANDS {
                mel_acc[b] += row[b] * p;
            }
        }
        for b in 0..NUM_MEL_BANDS {
            mel_frame[b] = (mel_acc[b] + LOG_EPS).ln() as f32;
        }

        spectrogram.push(mel_frame);
    }

    Ok(spectrogram)
}

/// Stack the three per-FFT log-mel spectrograms into a `[num_frames, 80, 3]`
/// tensor in the channel order dictated by FFT_SIZES, then apply per-bin
/// z-score normalization using the loaded `Normalizer` moments.
///
/// Returns a flat Vec<f32> of length `num_frames * 80 * 3` in C order
/// (frame-major, then mel-band, then fft-channel) — the exact layout the
/// exported ONNX graph expects for its `spectrogram` input.
fn stack_and_normalize(
    specs: [&[Vec<f32>]; 3],
    normalizer: &Normalizer,
) -> (Vec<f32>, usize) {
    // Different FFT sizes produce slightly different frame counts. Align
    // to the minimum so downstream indexing is uniform.
    let num_frames = specs[0].len().min(specs[1].len()).min(specs[2].len());

    let mut out = vec![0.0f32; num_frames * NUM_MEL_BANDS * FFT_SIZES.len()];
    for t in 0..num_frames {
        for b in 0..NUM_MEL_BANDS {
            for ch in 0..FFT_SIZES.len() {
                let raw = specs[ch][t][b];
                let mean = normalizer.mean[b][ch];
                let std = normalizer.std[b][ch];
                // Guard against a divide-by-zero if a training-time bin had
                // zero variance (shouldn't happen, but defensive).
                let denom = if std.abs() < f32::EPSILON { 1.0 } else { std };
                let idx = t * NUM_MEL_BANDS * FFT_SIZES.len() + b * FFT_SIZES.len() + ch;
                out[idx] = (raw - mean) / denom;
            }
        }
    }
    (out, num_frames)
}

// ═══════════════════════════════════════════════════════════════
// 4. ONNX INFERENCE
// ═══════════════════════════════════════════════════════════════

/// Run ddc_onset's placement CNN (CHALLENGE baked in) on the normalized
/// log-mel spectrogram. Returns per-frame onset probability in [0, 1].
///
/// Unlike the madmom pipeline, we do NOT chunk — the exported graph runs
/// in ~60 ms on CPU for a full 3-minute song (14k frames), so the complexity
/// of chunking buys nothing here.
fn run_onset_model(
    spec_flat: &[f32],
    num_frames: usize,
    model_path: &Path,
) -> Result<Vec<f32>, String> {
    let session_result = ONSET_SESSION.get_or_init(|| {
        (|| -> Result<Mutex<Session>, String> {
            let builder = Session::builder()
                .map_err(|e| format!("ONNX session builder failed: {}", e))?;
            let mut builder = builder
                .with_optimization_level(GraphOptimizationLevel::Level3)
                .map_err(|e| format!("ONNX optimization level failed: {}", e))?;
            let session = builder
                .commit_from_file(model_path)
                .map_err(|e| format!(
                    "Failed to load ddc_onset CNN from {}: {} — is ddc_onset_placement.onnx present and valid?",
                    model_path.display(), e
                ))?;
            Ok(Mutex::new(session))
        })()
    });

    let session_mutex = session_result.as_ref().map_err(|e| e.clone())?;
    let mut session = session_mutex.lock()
        .map_err(|e| format!("Session lock poisoned: {}", e))?;

    // Build the [num_frames, 80, 3] tensor. We own the data via to_vec() —
    // ort takes ownership of the tensor's backing storage.
    let input_array = Array3::<f32>::from_shape_vec(
        (num_frames, NUM_MEL_BANDS, FFT_SIZES.len()),
        spec_flat.to_vec(),
    ).map_err(|e| format!("Tensor shape error: {}", e))?;

    let input_tensor = Tensor::from_array(input_array)
        .map_err(|e| format!("ONNX tensor error: {}", e))?;

    let outputs = session.run(
        ort::inputs!["spectrogram" => input_tensor]
    ).map_err(|e| format!("ONNX inference error: {}", e))?;

    let (_shape, prob_data) = outputs["onset_probability"]
        .try_extract_tensor::<f32>()
        .map_err(|e| format!("ONNX output error: {}", e))?;

    Ok(prob_data.to_vec())
}

// ═══════════════════════════════════════════════════════════════
// 5. TAURI COMMANDS
// ═══════════════════════════════════════════════════════════════

/// Resolve the path of a model file inside the app's Tauri resource
/// directory. All three ddc_onset artifacts live under `resources/models/`.
fn resource_model_path(app_handle: &tauri::AppHandle, filename: &str) -> Result<PathBuf, String> {
    Ok(app_handle
        .path()
        .resource_dir()
        .map_err(|e| format!("Cannot resolve resource dir: {}", e))?
        .join("models")
        .join(filename))
}

/// Detect musically-meaningful onsets using the ddc_onset placement CNN.
///
/// Full pipeline: decode audio → 3 log-mel spectrograms with ddc_onset's
/// zero-phase windowing → per-bin normalization → ddc_onset CNN → silence
/// gate → OnsetBundle.
///
/// The model is loaded lazily on first call (~200 ms) and cached for the
/// lifetime of the app. For a 3-minute song the full pipeline takes
/// ~2 seconds on CPU (mel preprocessing dominates; inference is ~60 ms).
///
/// `music_path` must be an absolute filesystem path. For disk projects,
/// `chartStore.musicPath` is already absolute (the Rust backend
/// canonicalizes it on load). For imported charts the frontend writes the
/// blob to a temp file via `write_temp_audio` and passes that path.
#[tauri::command]
pub async fn detect_onsets_ml(
    music_path: String,
    app_handle: tauri::AppHandle,
) -> Result<OnsetBundle, String> {
    let placement_path = resource_model_path(&app_handle, "ddc_onset_placement.onnx")?;
    let extractor_path = resource_model_path(&app_handle, "ddc_onset_extractor.bin")?;
    let normalizer_path = resource_model_path(&app_handle, "ddc_onset_normalizer.bin")?;

    if !placement_path.exists() {
        return Err(format!(
            "Onset model not found at {}. Run scripts/convert_ddc_to_onnx.py first.",
            placement_path.display()
        ));
    }
    if !extractor_path.exists() {
        return Err(format!(
            "Extractor constants not found at {}. Run scripts/convert_ddc_to_onnx.py first.",
            extractor_path.display()
        ));
    }
    if !normalizer_path.exists() {
        return Err(format!(
            "Normalizer moments not found at {}. Run scripts/convert_ddc_to_onnx.py first.",
            normalizer_path.display()
        ));
    }

    // Move the entire CPU-bound pipeline to a blocking thread so we don't
    // freeze the Tauri async runtime (which handles all IPC commands).
    tauri::async_runtime::spawn_blocking(move || {
        let path = std::path::Path::new(&music_path);

        // 1. Decode audio.
        let samples = decode_audio_mono(path)?;

        // 2. Load (or re-read from cache) the extractor + normalizer constants.
        let extractor = EXTRACTOR.get_or_init(|| load_extractor(&extractor_path))
            .as_ref().map_err(|e| e.clone())?;
        let normalizer = NORMALIZER.get_or_init(|| load_normalizer(&normalizer_path))
            .as_ref().map_err(|e| e.clone())?;

        // 3. Compute 3 log-mel spectrograms in parallel. Each is independent
        //    (its own FFT planner + read-only samples slice), so rayon runs
        //    them on separate threads — wall-clock ≈ slowest single spectrogram
        //    instead of sum.
        let spectrograms: Vec<Vec<Vec<f32>>> = (0..FFT_SIZES.len())
            .into_par_iter()
            .map(|ch| {
                compute_log_mel_ddc(
                    &samples,
                    FFT_SIZES[ch],
                    &extractor.windows[ch],
                    &extractor.mels[ch],
                )
            })
            .collect::<Result<Vec<_>, String>>()?;

        // 4. Stack into [num_frames, 80, 3] and apply per-bin z-score.
        let (spec_flat, num_frames) = stack_and_normalize(
            [&spectrograms[0], &spectrograms[1], &spectrograms[2]],
            normalizer,
        );

        if num_frames == 0 {
            return Ok(OnsetBundle {
                version: ONSET_PIPELINE_VERSION,
                frames: Vec::new(),
            });
        }

        // 5. CNN inference (~60 ms on CPU for 3-min song).
        let mut probs = run_onset_model(&spec_flat, num_frames, &placement_path)?;

        // 6. Silence gate — zero probability in frames where the audio RMS
        //    is below the perceptible threshold. Same logic as the madmom
        //    pipeline (unchanged). Out-of-range indices can happen on the
        //    last 1-2 frames because num_frames is derived from the padded
        //    waveform; the bounds check handles those.
        for (i, prob) in probs.iter_mut().enumerate() {
            let start = i * HOP_SIZE;
            let end = (start + HOP_SIZE).min(samples.len());
            if start >= samples.len() || end <= start {
                *prob = 0.0;
                continue;
            }
            let mean_sq: f32 = samples[start..end].iter()
                .map(|&s| s * s)
                .sum::<f32>() / (end - start) as f32;
            if mean_sq < SILENCE_THRESHOLD {
                *prob = 0.0;
            }
        }

        // 7. Build per-frame OnsetResult. Time is derived from hop-aligned
        //    frame index: probability[i] → time i / FRAME_RATE seconds.
        let hop_seconds = HOP_SIZE as f64 / SAMPLE_RATE as f64;
        let frames: Vec<OnsetResult> = probs.iter().enumerate()
            .map(|(i, &prob)| OnsetResult {
                time: i as f64 * hop_seconds,
                probability: prob as f64,
            })
            .collect();

        Ok(OnsetBundle {
            version: ONSET_PIPELINE_VERSION,
            frames,
        })
    })
    .await
    .map_err(|e| format!("Onset detection task panicked: {}", e))?
}

/// Write audio bytes to a temporary file on disk so that `detect_onsets_ml`
/// can read it with symphonia. Called by the frontend when the chart was
/// imported (ZIP/RPE/PEC) and there is no disk file — only a blob URL.
#[tauri::command]
pub async fn write_temp_audio(
    audio_bytes: Vec<u8>,
    extension: String,
) -> Result<String, String> {
    let temp_dir = std::env::temp_dir().join("phichain-onset");

    std::fs::create_dir_all(&temp_dir)
        .map_err(|e| format!("Failed to create temp dir: {}", e))?;

    // Clean up old temp files from previous calls.
    if let Ok(entries) = std::fs::read_dir(&temp_dir) {
        for entry in entries.flatten() {
            let _ = std::fs::remove_file(entry.path());
        }
    }

    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let filename = format!("onset_{}.{}", nanos, extension);
    let file_path = temp_dir.join(&filename);

    std::fs::write(&file_path, &audio_bytes)
        .map_err(|e| format!("Failed to write temp audio: {}", e))?;

    Ok(file_path.to_string_lossy().into_owned())
}
